spring:
  application:
    name: murder-help
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/killer_mall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: killer_admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  sql:
    init:
      mode: never

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8080
  forward-headers-strategy: native

# JWT 설정
jwt:
  secret: "c3BhcnRhLXBheW1lbnQtand0LXNlY3JldC1rZXktZm9yLWJvb3RjYW1wLTIwMjYtdmVyeS1sb25nLXNlY3JldA=="  # Base64 encoded
  access-expiration: 1800000  # 1시간 (ms)
  refresh-expiration: 1209600000    

aws:
  s3:
    bucket: ${S3_BUCKET:murder-help-bucket}
    prefix: local
